---
- name: playbook to install httpd package
  hosts: all
  become: true
  tasks: 
  - name: httpd package installation
    yum: 
      name: httpd
      state: installed
    when: ansible_os_family == "RedHat"  
 
  - name: start httpd service
    service: 
      name: httpd
      state: started
    when: ansible_os_family == "RedHat"

  - name: install apache2 package
    apt:
      name: apache2
      state: present
    when: ansible_os_family == "Debian"  

  - name: start apache2 service
    service:
      name: apache2
      state: started
    when: ansible_os_family == "Debian"

  - name: copy
    copy:
      src: /opt/ansible/index.html
      dest: /var/www/html
      mode: 0666

