---
- name: playbook to install apache tomcat
  hosts: all
  become: true
  tasks: 
  - name: install java on RedHat distribution
    yum: 
      name: java
      state: installed
    when: ansible_os_family == "RedHat"

  - name: install java on Debian distribution
    apt: 
      name: default-jre
      state: present
    when: ansible_os_family == "Debian"
 
  - name: download tomcat packages
    get_url:
      url: https://mirrors.estointernet.in/apache/tomcat/tomcat-8/v8.5.59/bin/apache-tomcat-8.5.59.tar.gz
      dest: /opt

  - name: unarchive tomcat package
    unarchive:
      src: /opt/apache-tomcat-8.5.59.tar.gz
      dest: /opt
      remote_src: yes
  
  - name: provide execution permission to startup.sh file
    file:
      path: /opt/apache-tomcat-8.5.59/bin/startup.sh
      mode: 0777

  - name: start tomcat services
    shell: nohup ./startup.sh
    args:
      chdir: /opt/apache-tomcat-8.5.59/bin
      
      




